# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  app:
    image: node:lts # You can replace with specific node version you prefer
    working_dir: /usr/src/app
    volumes:
      - ./api/:/usr/src/app # Mounts your local app folder to the container
      - /usr/src/app/node_modules # Ensures node_modules persist inside the container
    ports:
      - "4512:3000" # Expose the Fastify app on localhost:3000
    command: sh -c "npm install && npm run dev" # Adjust command as needed (e.g., npm start)
    # environment:
    # - PORT=4513
    #   - HOST=${HOST}
    #   - NODE_ENV=${NODE_ENV}
    #   - CORS=${CORS}
    #   - LOG_LEVEL=${LOG_LEVEL}
    # - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    # - DATABASE_URL=${DATABASE_URL}
    # depends_on:
    # - db

  # db:
  #   env_file: ./data/.env
  #   image: postgres:latest # Use the PostgreSQL version you prefer
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data # Persist database data
  #
# volumes:
# postgres_data:
