# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  api:
    build:
      context: ./api
      target: api-dev
    env_file: ./api/.env
    environment:
      - POSTGRES_HOST=db #Override host for use Compose service

    develop:
      watch:
        - path: ./api
          action: sync
          target: /usr/local/app
          ignore:
            - node_modules/

        - path: ./api/package.json
          action: rebuild

        # If the schema changes must rebuild the container for type update
        - path: ./api/prisma
          action: rebuild

    # volumes:
    #   - ./api/:/usr/src/app # Mounts your local app folder to the container
    # - /usr/src/app/node_modules # Ensures node_modules persist inside the container
    ports:
      - "4512:4512" # Expose the Fastify app on localhost:3000
    depends_on:
      - db

  db:
    build:
      context: ./data
    env_file: ./data/.env
    image: postgres:latest # Use the PostgreSQL version you prefer
    ports:
      - "5432:5432" # Expose the Fastify app on localhost:3000

    # environment:
    # - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data:
